name: 'olist_dimensional_model'
version: '1.0.0'

profile: 'olist_dimensional_model'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  olist_dimensional_model:
    staging:
      +materialized: view
    dimensions:
      +materialized: table
    facts:
      +materialized: table
